name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Compile Binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/remote-server-linux ./cmd/server
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/remote-server-windows.exe ./cmd/server

          cp start-remote.sh dist/
          cp start-remote.ps1 dist/

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: "Latest Automatic Build"
          body: |
            Latest update commit: ${{ github.sha }}
          prerelease: true
          files: |
            dist/remote-server-linux
            dist/remote-server-windows.exe
            dist/start-remote.sh
            dist/start-remote.ps1
